#ifndef __ATTRIBUTE_H
#define __ATTRIBUTE_H

#include "main.h"

extern const unsigned int Attribute[];
extern const unsigned char CharToType[];

enum ObjectType {

    // update Attribute[] in attribute.c
    // update AnimateBase[] in animations.c

    TYPE_SPACE,                 // 00      ASSUMED == 0 in code
    TYPE_DIRT,                  // 01
    TYPE_BRICKWALL,             // 02
    TYPE_OUTBOX_PRE,            // 03
    TYPE_OUTBOX,                // 04
    TYPE_STEELWALL,             // 05
    TYPE_ROCK,                  // 06
    TYPE_DOGE,                  // 07
    TYPE_MELLON_HUSK_PRE,       // 08
    TYPE_MELLON_HUSK,           // 09
    TYPE_PEBBLE1,               // 10
    TYPE_DUST_0,                // 11
    TYPE_DOGE_FALLING,          // 12
    TYPE_ROCK_FALLING,          // 13
    TYPE_DUST_ROCK,             // 14
    TYPE_CONVERT_GEODE_TO_DOGE, // 15
    TYPE_SWITCH,                // 16
    TYPE_PUSHER,                // 17
    TYPE_PUSHER_VERT,           // 18
    TYPE_WYRM,                  // 19
    TYPE_GEODOGE,               // 20
    TYPE_GEODOGE_FALLING,       // 21
    TYPE_GEODOGE_CRITICAL,      // 22
    TYPE_LAVA,                  // 23
    TYPE_PEBBLE_ROCK,           // 24
    TYPE_FLIP_GRAVITY,          // 25
    TYPE_BLOCK,                 // 26
    TYPE_GRINDER,               // 27
    TYPE_HUB,                   // 28
    TYPE_WATER,                 // 29
    TYPE_WATERFLOW_0,           // 30
    TYPE_WATERFLOW_1,           // 31
    TYPE_WATERFLOW_2,           // 32
    TYPE_WATERFLOW_3,           // 33
    TYPE_WATERFLOW_4,           // 34
    TYPE_TAP,                   // 35
    TYPE_OUTLET,                // 36
    TYPE_GRINDER_1,             // 37
    TYPE_BELT,                  // 38
    TYPE_BELT_1,                // 39
    TYPE_CONVERT_PIPE,          // 40
    TYPE_DOGE_FALLING2,         // 41

    TYPE_MAX
};

enum ChName {

    // see charSet[] @ characterset.c
    // Objects numbered > 63 cannot be generated by cave data (6 bits)
    // see CharToType[] in attribute.c

    CH_BLANK,                  // 000
    CH_DIRT,                   // 001
    CH_BRICKWALL,              // 002
    CH_DOORCLOSED,             // 003
    CH_DOOROPEN_0,             // 004
    CH_EXITBLANK,              // 005
    CH_STEELWALL,              // 006
    CH_PEBBLE1,                // 007
    CH_PEBBLE2,                // 008
    CH_ROCK,                   // 009
    CH_ROCK_FALLING,           // 010          +2 offset assumed by code
    CH_DOGE_00,                // 011
    CH_DOGE_FALLING,           // 012          +2 offset assumed by code
    CH_MELLON_HUSK_BIRTH,      // 013
    CH_LAVA_BLANK,             // 014
    CH_LAVA_SMALL,             // 015
    CH_LAVA_MEDIUM,            // 016
    CH_LAVA_LARGE,             // 017
    CH_MELLON_HUSK,            // 018
    CH_DOGE_01,                // 019
    CH_DOGE_02,                // 020
    CH_DOGE_03,                // 021
    CH_DOGE_04,                // 022
    CH_DOGE_05,                // 023
    CH_DOGE_STATIC,            // 024 (CAN SWITCH ANIMATIONS ON THIS!)
    CH_PEBBLE_ROCK,            // 025
    CH_EXPLODETOBLANK_0,       // 026
    CH_EXPLODETOBLANK_1,       // 027
    CH_EXPLODETOBLANK_2,       // 028
    CH_EXPLODETOBLANK_3,       // 029
    CH_EXPLODETOBLANK_4,       // 030
    CH_DUST_0,                 // 031
    CH_DUST_1,                 // 032
    CH_DUST_2,                 // 033
    CH_GEODOGE,                // 034
    CH_CONGLOMERATE_1,         // 035
    CH_CONGLOMERATE_2,         // 036
    CH_CONGLOMERATE_3,         // 037
    CH_CONGLOMERATE_4,         // 038
    CH_CONGLOMERATE_5,         // 039
    CH_CONGLOMERATE_6,         // 040
    CH_CONGLOMERATE_7,         // 041
    CH_CONGLOMERATE_8,         // 042
    CH_CONGLOMERATE_9,         // 043
    CH_CONGLOMERATE_10,        // 044
    CH_CONGLOMERATE_11,        // 045
    CH_CONGLOMERATE_12,        // 046
    CH_CONGLOMERATE_13,        // 047
    CH_CONGLOMERATE_14,        // 048
    CH_CONGLOMERATE_15,        // 049
    CH_DUST_ROCK_0,            // 050
    CH_DUST_ROCK_1,            // 051
    CH_DUST_ROCK_2,            // 052
    CH_CONVERT_GEODE_TO_DOGE,  // 053
    CH_SWITCH_LEFT_OFF,        // 054
    CH_SWITCH_LEFT_ON,         // 055
    CH_HORIZONTAL_BAR,         // 056
    CH_PUSH_LEFT,              // 057       reverse must be +1
    CH_PUSH_LEFT_REVERSE,      // 058
    CH_PUSH_RIGHT,             // 059
    CH_PUSH_RIGHT_REVERSE,     // 060
    CH_VERTICAL_BAR,           // 061
    CH_PUSH_UP,                // 062
    CH_PUSH_UP_REVERSE,        // 063
    CH_PUSH_DOWN,              // 064
    CH_PUSH_DOWN_REVERSE,      // 065
    CH_WYRM_BODY,              // 066
    CH_WYRM_VERT_BODY,         // 067
    CH_WYRM_CORNER_LD,         // 068
    CH_WYRM_CORNER_RD,         // 069
    CH_WYRM_CORNER_LU,         // 070
    CH_WYRM_CORNER_RU,         // 071
    CH_WYRM_HEAD_U,            // 072
    CH_WYRM_HEAD_R,            // 073
    CH_WYRM_HEAD_D,            // 074
    CH_WYRM_HEAD_L,            // 075
    CH_CONGLOMERATE_MID,       // 076
    CH_GEODOGE_FALLING,        // 077
    CH_FLIP_GRAVITY_0,         // 078
    CH_FLIP_GRAVITY_1,         // 079
    CH_FLIP_GRAVITY_2,         // 080
    CH_BLOCK,                  // 081
    CH_GRINDER_0,              // 082
    CH_GRINDER_1,              // 083
    CH_HUB,                    // 084
    CH_WATER,                  // 085
    CH_WATERFLOW_0,            // 086 must be grouped
    CH_WATERFLOW_1,            // 087 .
    CH_WATERFLOW_2,            // 088 .
    CH_WATERFLOW_3,            // 089 .
    CH_WATERFLOW_4,            // 090 /
    CH_TAP_0,                  // 091
    CH_HUB_1,                  // 092
    CH_OUTLET,                 // 093
    CH_TAP_1,                  // 094
    CH_BELT_0,                 // 095
    CH_BELT_1,                 // 096
    CH_PUSH_DOWN2,             // 097
    CH_GEODOGE_CONVERT,        // 098
    CH_CONVERT_PIPE,           // 099
    CH_WYRM_TAIL_U,            // 100
    CH_WYRM_TAIL_R,            // 101
    CH_WYRM_TAIL_D,            // 102
    CH_WYRM_TAIL_L,            // 103
    CH_DOGE_FALLING_TOP,       // 104
    CH_DOGE_FALLING_BOTTOM,    // 105
    CH_ROCK_FALLING_TOP,       // 106
    CH_ROCK_FALLING_BOTTOM,    // 107
    CH_GEODOGE_FALLING_TOP,    // 108
    CH_GEODOGE_FALLING_BOTTOM, // 109
    CH_DOGE_FALLING_TOP2,      // 110
    CH_DOGE_FALLING_BOTTOM2,   // 111
    CH_DOGE_SIDE_1,            // 112
    CH_DOGE_SIDE_3,            // 113
    CH_DOGE_SIDE_2,            // 114
    CH_DOGE_SIDE_4,            // 115

    // 127 is limit

    CH_MAX
};

// clang-format off

#define ENUM_BIT_VALUE(counter) (1 << counter)

#define DEFINE_ENUM_WITH_BIT_VALUES(enumType, ...) \
    typedef enum { \
        __VA_ARGS__ \
    } enumType

#define ATT(enumConstant) ATT_##enumConstant = ENUM_BIT_VALUE(__COUNTER__)

DEFINE_ENUM_WITH_BIT_VALUES(TypeAttributes,

    ATT(ROLL),                  // 00
    ATT(CONVERT),               // 01
    ATT(EXPLODABLE),            // 02
    ATT(PERMEABLE),             // 03
    ATT(BLANK),                 // 04
    ATT(DIRT),                  // 05
    ATT(GRAB),                  // 06
    ATT(PUSH),                  // 07
    ATT(SQUASHABLE_TO_BLANKS),  // 08
    ATT(HARD),                  // 09
    ATT(EXIT),                  // 10
    ATT(NOROCKNOISE),           // 11
    ATT(BLANKISH),              // 12
    ATT(MINE),                  // 13
    ATT(WATERFLOW),             // 14
    ATT(CONVEYOR),              // 15
    ATT(GRIND),                 // 16
    ATT(PIPE),                  // 17
    ATT(PHASE4),                // 18
    ATT(PHASE2),                // 19
    ATT(PHASE1),                // 20
    ATT(DISSOLVES),             // 21
    ATT(MELTS),                 // 22
    ATT(GEODOGE),               // 23
    ATT(PAD),                   // 24
    ATT(CORNER),                // 25
);

#define POS_CORNER 25
#define VALUE_BREAK_GEODE 25

#endif
