# DO NOT DELETE

cavedata.o: defines_from_dasm_for_c.h main.h player.h atarivox.h bitpatterns.h
cavedata.o: rockford.h cavedata.h
characterset.o: main.h defines_from_dasm_for_c.h bitpatterns.h characterset.h
characterset.o: scroll.h
joystick.o: defines_cdfj.h main.h defines_from_dasm_for_c.h joystick.h
joystick.o: defines.h menu.h swipeCircle.h
random.o: random.h
swipeCircle.o: defines_cdfj.h main.h defines_from_dasm_for_c.h sound.h
swipeCircle.o: swipeCircle.h
animations.o: main.h defines_from_dasm_for_c.h animations.h attribute.h
animations.o: random.h
colour.o: defines.h defines_cdfj.h main.h defines_from_dasm_for_c.h
colour.o: cavedata.h colour.h score.h scroll.h
main.o: defines_cdfj.h defines.h main.h defines_from_dasm_for_c.h
main.o: animations.h attribute.h atarivox.h bitpatterns.h cavedata.h
main.o: characterset.h colour.h decodecaves.h drawplayer.h drawscreen.h
main.o: joystick.h menu.h overlay.h player.h random.h rockford.h score.h
main.o: scroll.h sound.h swipeCircle.h
rockford.o: defines_cdfj.h defines.h main.h defines_from_dasm_for_c.h
rockford.o: animations.h attribute.h atarivox.h player.h rockford.h random.h
rockford.o: score.h sound.h
atarivox.o: defines_from_dasm_for_c.h defines_cdfj.h main.h
decodecaves.o: defines_cdfj.h main.h defines_from_dasm_for_c.h decodecaves.h
decodecaves.o: attribute.h characterset.h random.h rockford.h
decodecaves.o: scroll.h
menu.o: defines.h defines_cdfj.h main.h defines_from_dasm_for_c.h menu.h
menu.o: atarivox.h bitpatterns.h cavedata.h colour.h joystick.h overlay.h
menu.o: player.h random.h sound.h
score.o: defines_cdfj.h main.h defines_from_dasm_for_c.h
score.o: bitpatterns.h rockford.h score.h sound.h swipeCircle.h
attribute.o: attribute.h main.h defines_from_dasm_for_c.h
drawplayer.o: defines_cdfj.h defines.h main.h defines_from_dasm_for_c.h
drawplayer.o: drawplayer.h swipeCircle.h colour.h attribute.h player.h
drawplayer.o: rockford.h scroll.h
overlay.o: defines_cdfj.h main.h defines_from_dasm_for_c.h defines.h
overlay.o: overlay.h player.h bitpatterns.h sound.h
scroll.o: defines_cdfj.h main.h defines_from_dasm_for_c.h player.h scroll.h
scroll.o: rockford.h
cavedata.o: main.h defines_from_dasm_for_c.h cavedata.h attribute.h
drawscreen.o: defines.h defines_cdfj.h main.h defines_from_dasm_for_c.h
drawscreen.o: animations.h attribute.h bitpatterns.h characterset.h
drawscreen.o: drawplayer.h drawscreen.h menu.h random.h scroll.h sound.h
sound.o: defines_cdfj.h main.h defines_from_dasm_for_c.h sound.h random.h
player.o: defines_from_dasm_for_c.h main.h player.h atarivox.h bitpatterns.h
player.o: rockford.h
